spring:
  application:
    name: petty

  config:
    import: "optional:classpath:application-secret.yml"

  profiles:
    active: dev

logging:
  level:
    io.github.petty: DEBUG
    org.springframework.web: INFO
    software.amazon.awssdk: INFO
    com.google.cloud: INFO
