spring:
  profiles:
    active: secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  config:
    import: "optional:classpath:application-secret.yml"
